### ISSUE TITLE
add support Forge - ForgeShreddedPaper

### ISSUE THREAD

**Issue by kitovoi111** [MultiPaper/ShreddedPaper#10]
### Is your feature request related to a problem?

add support Forge - ForgeShreddedPaper

### Describe the solution you'd like.

add support Forge - ForgeShreddedPaper

### Describe alternatives you've considered.

add support Forge - ForgeShreddedPaper

**Comment by PureGero** [comment]
Forge support will not be added to the ShreddedPaper project itself.
